import { TOKEN_PAIR_INFO } from '@/core/constants'

export const GET = 'GET'
export const SET = 'SET'
export const LOAD = 'LOAD'

// export const TOKENS_NAMESPACE = 'TOKENS'
// export const TOKEN_PAIRS_GETTER = 'GET_TOKEN_PAIRS'
// export const LOAD_TOKENS = `${TOKENS_NAMESPACE}/${LOAD}`
// export const GET_TOKENS = `${TOKENS_NAMESPACE}/${GET}`
// export const GET_TOKEN_PAIRS = `${TOKENS_NAMESPACE}/${TOKEN_PAIRS_GETTER}`

export const TOKEN_PAIR_SETTER = 'SET_TOKEN_PAIR'
export const SET_TOKEN_PAIR = `${TOKEN_PAIR_INFO}/${TOKEN_PAIR_SETTER}`

export const TRADEFORM_PRICE_SETTER = 'SET_TRADEFORM_PRICE'
export const SET_TRADEFORM_PRICE = `${TOKEN_PAIR_INFO}/${TRADEFORM_PRICE_SETTER}`

export const TRADEFORM_AMOUNT_SETTER = 'SET_TRADEFORM_AMOUNT'
export const SET_TRADEFORM_AMOUNT = `${TOKEN_PAIR_INFO}/${TRADEFORM_AMOUNT_SETTER}`

export const TRADEFORM_SIDE_SETTER = 'SET_TRADEFORM_SIDE'
export const SET_TRADEFORM_SIDE = `${TOKEN_PAIR_INFO}/${TRADEFORM_SIDE_SETTER}`
