import { 
	TOKEN_PAIR_NAMESPACE, 
	WALLET_NAMESPACE, 
	DEPOSIT_FORM_NAMESPACE,
	ALL_OPEN_ORDERS_NAMESPACE,
	USER_TRADE_HISTORY_NAMESPACE,
	WALLET_BALANCES_NAMESPACE,
	WITHDRAW_REQUESTS_NAMESPACE,
	GLOBAL_ERRORS_NAMESPACE
} from '@/core/constants'

export const TOKEN_PAIR_SETTER = 'SET_TOKEN_PAIR'
export const SET_TOKEN_PAIR = `${TOKEN_PAIR_NAMESPACE}/${TOKEN_PAIR_SETTER}`
export const SOCKET_SERVER_DIALER = 'CONNECT_SOCKET_SERVER'
export const CONNECT_SOCKET_SERVER = `${TOKEN_PAIR_NAMESPACE}/${SOCKET_SERVER_DIALER}`
export const SOCKET_SERVER_CLOSER = 'DISCONNECT_SOCKET_SERVER'
export const DISCONNECT_SOCKET_SERVER = `${TOKEN_PAIR_NAMESPACE}/${SOCKET_SERVER_CLOSER}`

// Trade form
export const TRADEFORM_PRICE_SETTER = 'SET_TRADEFORM_PRICE'
export const SET_TRADEFORM_PRICE = `${TOKEN_PAIR_NAMESPACE}/${TRADEFORM_PRICE_SETTER}`

export const TRADEFORM_AMOUNT_SETTER = 'SET_TRADEFORM_AMOUNT'
export const SET_TRADEFORM_AMOUNT = `${TOKEN_PAIR_NAMESPACE}/${TRADEFORM_AMOUNT_SETTER}`

export const TRADEFORM_SIDE_SETTER = 'SET_TRADEFORM_SIDE'
export const SET_TRADEFORM_SIDE = `${TOKEN_PAIR_NAMESPACE}/${TRADEFORM_SIDE_SETTER}`

// Wallet
export const CONNECT = 'CONNECT'
export const DISCONNECT = 'DISCONNECT'
export const CONNECT_WALLET = `${WALLET_NAMESPACE}/${CONNECT}`
export const DISCONNECT_WALLET = `${WALLET_NAMESPACE}/${DISCONNECT}`

// Deposit Form
export const DEPOSITFORM_GASPRICE_SETTER = 'SET_DEPOSITFORM_GASPRICE'
export const SET_DEPOSITFORM_GASPRICE = `${DEPOSIT_FORM_NAMESPACE}/${DEPOSITFORM_GASPRICE_SETTER}`

export const DEPOSITFORM_AMOUNT_SETTER = 'SET_DEPOSITFORM_AMOUNT'
export const SET_DEPOSITFORM_AMOUNT = `${DEPOSIT_FORM_NAMESPACE}/${DEPOSITFORM_AMOUNT_SETTER}`

export const DEPOSITFORM_TOKEN_SETTER = 'SET_DEPOSITFORM_TOKEN'
export const SET_DEPOSITFORM_TOKEN = `${DEPOSIT_FORM_NAMESPACE}/${DEPOSITFORM_TOKEN_SETTER}`

// Chart Data
export const OHLC_CHARTDATA_GETTER = 'FETCH_OHLC_CHARTDATA'
export const FETCH_OHLC_CHARTDATA = `${TOKEN_PAIR_NAMESPACE}/${OHLC_CHARTDATA_GETTER}`

// Trade History
export const TRADE_HISTORY_GETTER = 'FETCH_TRADE_HISTORY'
export const FETCH_TRADE_HISTORY = `${TOKEN_PAIR_NAMESPACE}/${TRADE_HISTORY_GETTER}`
export const TRADE_HISTORY_APPENDER = 'APPEND_TRADE_HISTORY'
export const APPEND_TRADE_HISTORY = `${TOKEN_PAIR_NAMESPACE}/${TRADE_HISTORY_APPENDER}`

// Orderbook
export const PAIR_ORDERBOOK_GETTER = 'FETCH_PAIR_ORDERBOOK'
export const FETCH_PAIR_ORDERBOOK = `${TOKEN_PAIR_NAMESPACE}/${PAIR_ORDERBOOK_GETTER}`
export const FILL_ORDERBOOK_ORDER = `FILL_ORDERBOOK_ORDER`
export const ADD_ORDERBOOK_ORDER = `ADD_ORDERBOOK_ORDER`
export const CANCEL_ORDERBOOK_ORDER = `CANCEL_ORDERBOOK_ORDER`

// My orders
export const USER_PAIR_ORDERS_GETTER = 'FETCH_USER_PAIR_ORDERS'
export const FETCH_USER_PAIR_ORDERS = `${TOKEN_PAIR_NAMESPACE}/${USER_PAIR_ORDERS_GETTER}`
export const PAIR_ORDERS_ORDER_REMOVER = 'REMOVE_ORDER_FROM_OPEN_ORDERS'
export const REMOVE_ORDER_FROM_OPEN_ORDERS = `${TOKEN_PAIR_NAMESPACE}/${PAIR_ORDERS_ORDER_REMOVER}`
export const FILL_OPENORDER_ORDER = `FILL_OPENORDER_ORDER`
export const ADD_OPENORDER_ORDER = `ADD_OPENORDER_ORDER`

// All open orders
export const USER_OPEN_ORDERS_GETTER = 'FETCH_USER_OPEN_ORDERS'
export const FETCH_ALL_OPEN_ORDERS = `${ALL_OPEN_ORDERS_NAMESPACE}/${USER_OPEN_ORDERS_GETTER}`
export const ALL_OPEN_ORDERS_REMOVER = `ALL_OPEN_ORDERS_REMOVER`
export const REMOVE_ORDER_FROM_ALL_OPEN_ORDERS = `${ALL_OPEN_ORDERS_NAMESPACE}/${ALL_OPEN_ORDERS_REMOVER}`

// User trades
export const ALL_USER_TRADES_GETTER = 'FETCH_USER_TRADE_HISTORY'
export const FETCH_USER_TRADE_HISTORY = `${USER_TRADE_HISTORY_NAMESPACE}/${ALL_USER_TRADES_GETTER}`

// User trades
export const WALLET_BALANCES_GETTER = 'FETCH_WALLET_BALANCES'
export const FETCH_WALLET_BALANCES = `${WALLET_BALANCES_NAMESPACE}/${WALLET_BALANCES_GETTER}`

// Withdraw Requests
export const WITHDRAW_REQUESTS_GETTER = 'FETCH_WITHDRAW_REQUESTS'
export const FETCH_WITHDRAW_REQUESTS = `${WITHDRAW_REQUESTS_NAMESPACE}/${WITHDRAW_REQUESTS_GETTER}`
