export const COMMIT_TOKEN_PAIR = 'COMMIT_TOKEN_PAIR'
export const COMMIT_TRADEFORM_PRICE = 'COMMIT_TRADEFORM_PRICE'
export const COMMIT_TRADEFORM_AMOUNT = 'COMMIT_TRADEFORM_AMOUNT'
export const COMMIT_TRADEFORM_SIDE = 'COMMIT_TRADEFORM_SIDE'