export const COMMIT_TOKEN_PAIR = 'COMMIT_TOKEN_PAIR'
export const COMMIT_TRADEFORM_PRICE = 'COMMIT_TRADEFORM_PRICE'
export const COMMIT_TRADEFORM_AMOUNT = 'COMMIT_TRADEFORM_AMOUNT'
export const COMMIT_TRADEFORM_SIDE = 'COMMIT_TRADEFORM_SIDE'

export const COMMIT_CONNECT_WALLET = 'COMMIT_CONNECT_WALLET'
export const COMMIT_DISCONNECT_WALLET = 'COMMIT_DISCONNECT_WALLET'

export const COMMIT_DEPOSITFORM_GASPRICE = 'COMMIT_DEPOSITFORM_GASPRICE'
export const COMMIT_DEPOSITFORM_AMOUNT = 'COMMIT_DEPOSITFORM_AMOUNT'
export const COMMIT_DEPOSITFORM_TOKEN = 'COMMIT_DEPOSITFORM_TOKEN'