export const COMMIT_TOKEN_PAIR = 'COMMIT_TOKEN_PAIR'

export const COMMIT_CONNECT_SOCKET_SERVER = 'COMMIT_CONNECT_SOCKET_SERVER'
export const COMMIT_DISCONNECT_SOCKET_SERVER = 'COMMIT_DISCONNECT_SOCKET_SERVER'

export const COMMIT_TRADEFORM_PRICE = 'COMMIT_TRADEFORM_PRICE'
export const COMMIT_TRADEFORM_AMOUNT = 'COMMIT_TRADEFORM_AMOUNT'
export const COMMIT_TRADEFORM_SIDE = 'COMMIT_TRADEFORM_SIDE'

export const COMMIT_CONNECT_WALLET = 'COMMIT_CONNECT_WALLET'
export const COMMIT_DISCONNECT_WALLET = 'COMMIT_DISCONNECT_WALLET'

export const COMMIT_DEPOSITFORM_GASPRICE = 'COMMIT_DEPOSITFORM_GASPRICE'
export const COMMIT_DEPOSITFORM_AMOUNT = 'COMMIT_DEPOSITFORM_AMOUNT'
export const COMMIT_DEPOSITFORM_TOKEN = 'COMMIT_DEPOSITFORM_TOKEN'

export const COMMIT_OHLC_CHARTDATA = 'COMMIT_OHLC_CHARTDATA'

export const COMMIT_TRADE_HISTORY = 'COMMIT_TRADE_HISTORY'
export const COMMIT_NEW_TRADE = 'COMMIT_NEW_TRADE'

export const COMMIT_PAIR_ORDERBOOK = 'COMMIT_PAIR_ORDERBOOK'

export const COMMIT_USER_PAIR_ORDERS = 'COMMIT_USER_PAIR_ORDERS'